[package]
name = "book_worm"
version = "0.1.0"
authors = ["Nick Benoit <nick.benoit14@gmail.com>"]

[dependencies]
postgres = "0.15"
rocket = "0.3.0"
rocket_contrib = "0.3.0"
rocket_codegen = "0.3.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

